#!/usr/bin/env sh

# Check if the talk2text-editor is already running
if [ "$(swaymsg -t get_tree | jq '[.. | objects | select(.app_id == "talk2text-editor")] | length')" -gt 0 ]; then
  swaymsg '[app_id="talk2text-editor"] scratchpad show' >/dev/null
  exit 0
fi

transcript_file="$1"
context_file="$2"
work_dir="$(dirname "$transcript_file")"
luafile="$work_dir/talk2text.lua"
if ! [ -e "$luafile" ]; then
  cat > "$luafile" <<'EOF'
vim.api.nvim_create_autocmd('VimEnter', {
  once = true,
  callback = function()
    vim.api.nvim_win_set_height(vim.api.nvim_get_current_win(), math.floor(vim.o.lines * 0.75))
    local buf = vim.fn.bufnr(vim.fn.argv(0))
    vim.keymap.set('n', 'qq', function()
      vim.fn.setreg('+', vim.api.nvim_buf_get_lines(buf, 0, -1, false), 'l')
      vim.api.nvim_buf_set_lines(buf, 0, -1, false, {})
      vim.cmd('wqa!')
    end)
  end,
})
EOF
fi

# Ensure the window rules are in place before launching
swaymsg "exec alacritty --class talk2text-editor --title talk2text --working-directory \"$work_dir\" --command nvim -o \"$transcript_file\" \"$context_file\" -c 'luafile $luafile'" >/dev/null
