package amrwb

import (
	"crypto/sha256"
	"errors"
	"fmt"
	"testing"

	"github.com/edmonl/talk2text/internal/amrwb/native"
)

func TestDecodeKnownFrame(t *testing.T) {
	size, _ := native.FrameSize(0x04)
	encoded := append([]byte(Magic), 0x04)
	encoded = append(encoded, make([]byte, size-1)...)

	pcm, err := Decode(encoded, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(pcm) != pcmBytesPerFrame {
		t.Fatalf("decoded PCM length = %d, want %d", len(pcm), pcmBytesPerFrame)
	}

	// Generated by the unmodified opencore-amr 0.1.6 amrwb-dec example.
	const wantSHA256 = "5c89afd3c80ea5a729a668a97579bf81d3cc326d03687ca942b52e5dec1649b9"
	if got := fmt.Sprintf("%x", sha256.Sum256(pcm)); got != wantSHA256 {
		t.Fatalf("decoded PCM SHA-256 = %s, want %s", got, wantSHA256)
	}
}

func TestDecodeAllFrameTypes(t *testing.T) {
	encoded := []byte(Magic)
	frameCount := 0
	for frameType := 0; frameType < 16; frameType++ {
		size, valid := native.FrameSize(byte(frameType << 3))
		if !valid {
			continue
		}
		encoded = append(encoded, byte(frameType<<3)|0x04)
		encoded = append(encoded, make([]byte, size-1)...)
		frameCount++
	}

	pcm, err := Decode(encoded, frameCount)
	if err != nil {
		t.Fatal(err)
	}
	if want := frameCount * pcmBytesPerFrame; len(pcm) != want {
		t.Fatalf("decoded PCM length = %d, want %d", len(pcm), want)
	}
}

func TestDecodeHeaderOnly(t *testing.T) {
	pcm, err := Decode([]byte(Magic), 0)
	if err != nil {
		t.Fatal(err)
	}
	if pcm == nil || len(pcm) != 0 {
		t.Fatalf("decoded PCM = %#v, want non-nil empty slice", pcm)
	}
}

func TestDecodeIgnoresStoragePaddingBits(t *testing.T) {
	pcm, err := Decode(append([]byte(Magic), 0xff), 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(pcm) != pcmBytesPerFrame {
		t.Fatalf("decoded PCM length = %d, want %d", len(pcm), pcmBytesPerFrame)
	}
}

func TestDecodeBadQualityFrame(t *testing.T) {
	size, _ := native.FrameSize(0x00)
	encoded := append([]byte(Magic), 0x00)
	encoded = append(encoded, make([]byte, size-1)...)

	pcm, err := Decode(encoded, 1)
	if err != nil {
		t.Fatal(err)
	}
	if len(pcm) != pcmBytesPerFrame {
		t.Fatalf("decoded PCM length = %d, want %d", len(pcm), pcmBytesPerFrame)
	}
}

func TestDecodeRejectsInvalidInput(t *testing.T) {
	tests := []struct {
		name    string
		data    []byte
		wantErr error
	}{
		{
			name:    "empty",
			wantErr: ErrInvalidHeader,
		},
		{
			name:    "wrong header",
			data:    []byte("#!AMR\n"),
			wantErr: ErrInvalidHeader,
		},
		{
			name:    "multichannel header",
			data:    []byte("#!AMR-WB_MC1.0\n"),
			wantErr: ErrInvalidHeader,
		},
		{
			name:    "reserved frame type",
			data:    append([]byte(Magic), byte(10<<3)|0x04),
			wantErr: ErrInvalidFrame,
		},
		{
			name:    "truncated speech frame",
			data:    append([]byte(Magic), 0x04),
			wantErr: ErrInvalidFrame,
		},
		{
			name: "truncated trailing frame",
			data: append(
				append([]byte(Magic), 0x7c),
				0x04,
			),
			wantErr: ErrInvalidFrame,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if _, err := Decode(tt.data, len(tt.data)); !errors.Is(err, tt.wantErr) {
				t.Fatalf("Decode() error = %v, want %v", err, tt.wantErr)
			}
		})
	}
}

func TestDecodeRejectsTooManyFrames(t *testing.T) {
	encoded := append([]byte(Magic), 0x7c, 0x7c)

	if _, err := Decode(encoded, 1); !errors.Is(err, ErrTooLong) {
		t.Fatalf("Decode() error = %v, want %v", err, ErrTooLong)
	}
}

func FuzzDecode(f *testing.F) {
	f.Add([]byte(Magic))
	f.Add(append([]byte(Magic), 0x7c))
	f.Add(append([]byte(Magic), 0x04))
	f.Add([]byte("not AMR-WB"))

	f.Fuzz(func(t *testing.T, data []byte) {
		_, _ = Decode(data, 100)
	})
}
